<a href="https://colab.research.google.com/github/javedmatrah/AIQ2/blob/main/fashion_mnist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
from tensorflow.keras.datasets import fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

In [23]:
train_images.shape

(60000, 28, 28)

In [24]:
train_labels

array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

In [25]:
test_images.shape

(10000, 28, 28)

In [26]:
test_labels

array([9, 2, 1, ..., 8, 1, 5], dtype=uint8)

In [ ]:
import matplotlib.pyplot as plt

digit = train_images[0]
print("Class Label:",train_labels[0])
print(digit.shape)

plt.imshow(digit, cmap=plt.cm.binary)
plt.show()

In [28]:
import numpy as np
print(train_labels)
print(np.unique(train_labels))

[9 0 0 ... 3 0 5]
[0 1 2 3 4 5 6 7 8 9]


In [29]:
print(test_labels)
print(np.unique(test_labels))

[9 2 1 ... 8 1 5]
[0 1 2 3 4 5 6 7 8 9]


#Listing 2.2 The network architecture

In [30]:
from tensorflow.keras import models
from tensorflow.keras import layers

network = models.Sequential()


network.add(layers.Dense(512, activation='relu', input_shape=(28*28, )))
network.add(layers.Dense(10, activation='softmax'))

#Listing 2.3 The compilation step

In [31]:
network.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

In [32]:
train_images.ndim

3

#Listing 2.4 Preparing the image data

In [33]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255 #Normalization


test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255 #Normalization

#Listing 2.5 Preparing the labels

In [34]:
train_labels[0]

9

#One-Hot-Encoding

In [35]:
from tensorflow.keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [19]:
train_labels[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)

#Now Train your Model

In [36]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 5s 9ms/step - loss: 0.5583 - accuracy: 0.8006
Epoch 2/5
469/469 [==============================] - 4s 9ms/step - loss: 0.3805 - accuracy: 0.8602
Epoch 3/5
469/469 [==============================] - 4s 9ms/step - loss: 0.3374 - accuracy: 0.8754
Epoch 4/5
469/469 [==============================] - 4s 9ms/step - loss: 0.3094 - accuracy: 0.8863
Epoch 5/5
469/469 [==============================] - 4s 9ms/step - loss: 0.2916 - accuracy: 0.8938


In [37]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_acc:', test_acc)

313/313 [==============================] - 1s 2ms/step - loss: 0.3369 - accuracy: 0.8818
test_acc: 0.8817999958992004


#Using the model to make predictions

In [39]:
test_digits = test_images[0:10]
predictions = network.predict(test_digits)
predictions[0]

array([6.4240474e-08, 2.9841175e-11, 2.9196954e-09, 1.1704699e-09,
       2.5541238e-09, 3.3441521e-02, 1.2631189e-07, 6.1448445e-03,
       9.3763119e-05, 9.6031976e-01], dtype=float32)

In [40]:
predictions[0].argmax()

9

In [56]:
predictions[0][7].argmax()

0

In [54]:
test_labels[0].argmax()

9

In [43]:
predictions[1].argmax()

2

In [50]:
predictions[0][1].argmax()

0

In [49]:
test_labels[1].argmax()

2

In [46]:
predictions[2].argmax()

1

In [48]:
test_labels[2].argmax()

1

In [51]:
predictions[3].argmax()

1

In [53]:
test_labels[3].argmax()

1