In [1]:
import numpy as np

In [4]:
x=np.zeros((4,4))

In [5]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.empty((1,1))

array([[1.73984195e+228]])

In [17]:
l=[1,2,3,4,5]

In [18]:
np.array(l)

array([1, 2, 3, 4, 5])

In [19]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

### 4.Arithmetic with ndarray

In [23]:
a=np.random.randn((10))

In [24]:
b=np.random.randn((10))

In [25]:
a

array([ 0.25353031, -0.98372946, -0.54450451, -0.18084478, -0.11342976,
       -0.56668055, -0.86239306, -0.10976343,  0.92992665, -1.03322586])

In [26]:
b

array([ 0.12191381, -1.79316842,  0.14083963, -1.00526999, -0.33392756,
        0.87462364, -0.51816416, -0.90080346,  1.11665234, -1.63476051])

In [27]:
a+b

array([ 0.37544412, -2.77689788, -0.40366488, -1.18611477, -0.44735732,
        0.3079431 , -1.38055722, -1.01056689,  2.04657899, -2.66798637])

In [28]:
a-b

array([ 0.1316165 ,  0.80943896, -0.68534414,  0.8244252 ,  0.22049781,
       -1.44130419, -0.3442289 ,  0.79104003, -0.18672568,  0.60153465])

In [29]:
1/a

array([ 3.94430158, -1.01653965, -1.83653208, -5.52960375, -8.81602883,
       -1.76466265, -1.15956406, -9.11050239,  1.07535363, -0.9678426 ])

In [30]:
a=a>0

In [31]:
a

array([ True, False, False, False, False, False, False, False,  True,
       False])

In [32]:
a[a>0]

array([ True,  True])

### 5. Indexing & Slicing

In [35]:
x= np.array([1,7,9,8,5])

In [36]:
x[x>5]

array([7, 9, 8])

In [37]:
x[[2,1]] #Return elements at index 2 & 1

array([9, 7])

In [38]:
 y=np.random.randn(10,10)

In [40]:
y

array([[ 2.5420197 , -1.36941471, -0.9471568 ,  0.37158599,  0.83595864,
         1.18613455, -1.04795691,  0.08865065,  3.18860979,  0.90033103],
       [-0.95033267,  0.56498828, -1.33784365, -1.38235383, -0.68949862,
         0.53383394,  0.72954949,  0.66120752, -0.11646387,  1.96983957],
       [-0.24742308, -0.15813637,  0.45770564,  0.99100568,  0.15858081,
         0.87236717,  0.44148897, -1.79774258, -1.98338568, -0.62315681],
       [-0.39649533,  0.4997728 , -1.52672512,  0.55218719, -1.12622819,
        -0.0881873 , -0.8627822 , -1.67594515,  2.04307905,  1.30849801],
       [ 0.48598566, -0.06659739, -1.30878746,  0.57745388,  0.89160799,
        -0.08607024,  3.06177189,  0.16407595, -0.87317651, -1.78734054],
       [-1.29594024,  0.21546672,  0.53640033,  0.215481  , -0.59966736,
         0.0926722 , -1.62834964,  0.9108098 ,  1.91389268, -1.41752492],
       [-0.91418809, -0.85928498, -0.77546338,  2.10604581, -1.16276342,
        -0.513421  , -1.71375155,  1.04663595

In [41]:
y[0] #Returns first row

array([ 2.5420197 , -1.36941471, -0.9471568 ,  0.37158599,  0.83595864,
        1.18613455, -1.04795691,  0.08865065,  3.18860979,  0.90033103])

In [46]:
# y[1:10:2,:] #Returns odd rows
# y[1:10:2,::] #Returns odd rows
y[1:10:2] #Returns odd rows

array([[-0.95033267,  0.56498828, -1.33784365, -1.38235383, -0.68949862,
         0.53383394,  0.72954949,  0.66120752, -0.11646387,  1.96983957],
       [-0.39649533,  0.4997728 , -1.52672512,  0.55218719, -1.12622819,
        -0.0881873 , -0.8627822 , -1.67594515,  2.04307905,  1.30849801],
       [-1.29594024,  0.21546672,  0.53640033,  0.215481  , -0.59966736,
         0.0926722 , -1.62834964,  0.9108098 ,  1.91389268, -1.41752492],
       [ 0.60518027, -0.48254005,  0.51295424, -0.83003052,  0.4670929 ,
         0.41239538,  0.34950347,  0.19297333,  1.23039219,  0.3194755 ],
       [-0.79099199,  1.28895181, -0.93776649, -1.94962861,  0.95302061,
         0.78232304,  0.48981132,  0.46677885,  0.13181993,  0.16700354]])

In [63]:
z= np.ones((5,5))

In [70]:
z[1:1,2]=5
z

array([[5., 5., 5., 5., 5.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [62]:
z[2:-1,2:-1]=0

In [58]:
z

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### 6.Fast element-wise array functions

In [97]:
x=([1,2,3,4,5])

In [98]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [99]:
np.square(x)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [100]:
np.max(x)

5

### 7. Np.where 

In [94]:
salary=np.array([0,-1,50000,45000,30000])

In [96]:
np.where(salary<=0,40000,salary)

array([40000, 40000, 50000, 45000, 30000])

### 8.Mathematical & Statistical Methods

In [71]:
x=np.array([1,3,5,6,8,9])

In [72]:
x.mean()

5.333333333333333

In [75]:
x.cumsum()

array([ 1,  4,  9, 15, 23, 32], dtype=int32)

In [76]:
x.cumprod()

array([   1,    3,   15,   90,  720, 6480], dtype=int32)

In [79]:
y=x[x>5]

In [80]:
y

array([6, 8, 9])

In [81]:
y.sum()

23

In [82]:
y.all()

True

In [83]:
y.any()

True

In [84]:
y.sort()

In [85]:
y

array([6, 8, 9])

In [86]:
x.sort()
x

array([1, 3, 5, 6, 8, 9])

In [89]:
np.unique(x)

array([1, 3, 5, 6, 8, 9])

In [90]:
np.unique(y)

array([6, 8, 9])

### 9.File Input Output

In [103]:
print(x)
print(y)

[1, 2, 3, 4, 5]
[6 8 9]


In [114]:
np.savez('textxy',x,y)

In [115]:
loadxy=np.load('testxy.npz')
loadxy['x']

FileNotFoundError: [Errno 2] No such file or directory: 'testxy.npz'

NameError: name 'MMMM' is not defined

### 10. Linear Algebra Functions 

In [117]:
x=np.random.randn(3,2)

In [118]:
y=np.random.randn(2,3)

In [119]:
print(x)
print(y)

[[ 0.22568163  1.29782859]
 [-2.2935669   0.50646779]
 [-0.01459533  0.09165597]]
[[-1.22110309  1.0563861  -1.10689978]
 [-0.44168161 -2.08553165  0.6014253 ]]


In [120]:
x.dot(y)

array([[-0.84880755, -2.46825568,  0.53074001],
       [ 2.57698411, -3.47914682,  2.84335124],
       [-0.02266036, -0.20656973,  0.07127979]])

In [121]:
x.transpose()

array([[ 0.22568163, -2.2935669 , -0.01459533],
       [ 1.29782859,  0.50646779,  0.09165597]])

### 11. Pseudo Random Number 

In [122]:
np.random.seed(7)

In [123]:
np.random.normal(size=(3,3))

array([[ 1.69052570e+00, -4.65937371e-01,  3.28201637e-02],
       [ 4.07516283e-01, -7.88923029e-01,  2.06557291e-03],
       [-8.90385858e-04, -1.75472431e+00,  1.01765801e+00]])

In [125]:
np.random.uniform(size=(3,4))

array([[0.66901324, 0.46775286, 0.20484909, 0.49076589],
       [0.37238469, 0.47740115, 0.36589039, 0.83791799],
       [0.76864751, 0.31399468, 0.57262533, 0.27604905]])

### 12 NumPy Advanced Array Manipulations 

### 13 Reshape

In [136]:
x=np.random.randn(4,5)

In [137]:
x

array([[ 0.15433554,  1.76616088, -0.32941375,  0.84073324, -0.1799864 ],
       [ 0.56806189, -0.7528372 , -1.7083392 , -1.80309866,  0.38312185],
       [ 2.24759505,  0.26941163, -0.52460462,  1.91201886,  0.23730185],
       [ 0.10143399,  0.25257774, -0.1323772 , -0.30947634, -1.43496347]])

In [138]:
x.reshape(5,4)

array([[ 0.15433554,  1.76616088, -0.32941375,  0.84073324],
       [-0.1799864 ,  0.56806189, -0.7528372 , -1.7083392 ],
       [-1.80309866,  0.38312185,  2.24759505,  0.26941163],
       [-0.52460462,  1.91201886,  0.23730185,  0.10143399],
       [ 0.25257774, -0.1323772 , -0.30947634, -1.43496347]])

In [147]:
x.reshape(2,2,5)

array([[[ 0.15433554,  1.76616088, -0.32941375,  0.84073324,
         -0.1799864 ],
        [ 0.56806189, -0.7528372 , -1.7083392 , -1.80309866,
          0.38312185]],

       [[ 2.24759505,  0.26941163, -0.52460462,  1.91201886,
          0.23730185],
        [ 0.10143399,  0.25257774, -0.1323772 , -0.30947634,
         -1.43496347]]])

In [150]:
x.ravel() #This will flatten the array into a singe dimension
x.flatten()

array([ 0.15433554,  1.76616088, -0.32941375,  0.84073324, -0.1799864 ,
        0.56806189, -0.7528372 , -1.7083392 , -1.80309866,  0.38312185,
        2.24759505,  0.26941163, -0.52460462,  1.91201886,  0.23730185,
        0.10143399,  0.25257774, -0.1323772 , -0.30947634, -1.43496347])

### 14 Concatenate 

In [151]:
print(x)
print(y)

[[ 0.15433554  1.76616088 -0.32941375  0.84073324 -0.1799864 ]
 [ 0.56806189 -0.7528372  -1.7083392  -1.80309866  0.38312185]
 [ 2.24759505  0.26941163 -0.52460462  1.91201886  0.23730185]
 [ 0.10143399  0.25257774 -0.1323772  -0.30947634 -1.43496347]]
[[-1.22110309  1.0563861  -1.10689978]
 [-0.44168161 -2.08553165  0.6014253 ]]


In [156]:
x=[[1,2,3],[4,5,6]]
arr1=np.array(x)

In [157]:
y=[[7,8,9],[10,11,12]]
arr2=np.array(y)

In [167]:
print(x)
print(y)

[[1, 2, 3], [4, 5, 6]]
[[7, 8, 9], [10, 11, 12]]


In [161]:
np.concatenate(arr1,arr2,axis=1)

TypeError: concatenate() got multiple values for argument 'axis'

In [165]:
np.vstack((arr1,arr2)) #Concatenation Row wise

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [166]:
np.hstack((arr1,arr2)) #Concatenation column wise

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### 15 Split 

In [168]:
x

[[1, 2, 3], [4, 5, 6]]

In [169]:
x=[1,2,3,4,5,6,7,8,9]

In [170]:
x

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [173]:
np.split(x,[2,5]) #Split the array at position 2 & 5

[array([1, 2]), array([3, 4, 5]), array([6, 7, 8, 9])]

In [174]:
x=[[1,2,3,4,5,6,7,8,9],[10,11,12,13,14,15,16,17,18]]
x

[[1, 2, 3, 4, 5, 6, 7, 8, 9], [10, 11, 12, 13, 14, 15, 16, 17, 18]]

In [175]:
np.array(x)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [178]:
np.split(x,[4,6], axis=1)

[array([[ 1,  2,  3,  4],
        [10, 11, 12, 13]]),
 array([[ 5,  6],
        [14, 15]]),
 array([], shape=(2, 0), dtype=int32)]

### 16 Tile & Repeat 

In [193]:
x

[[1, 2, 3, 4, 5, 6, 7, 8, 9], [10, 11, 12, 13, 14, 15, 16, 17, 18]]

In [194]:
x=[1,2,3,4,5]

In [195]:
np.repeat(x,2)

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5])

In [196]:
np.tile(x,2)

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])