# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
x=np.zeros(10)

In [4]:
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [5]:
v = np.arange(10,50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [6]:
np.shape(v)

(40,)

5. Print the type of the previous array in question 3

In [7]:
type(v)

numpy.ndarray

6. Print the numpy version and the configuration


In [8]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
None


7. Print the dimension of the array in question 3


In [9]:
np.ndim(x)

1

8. Create a boolean array with all the True values

In [10]:
b_a =np.ones((5,5), dtype=bool)
b_a

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

9. Create a two dimensional array




In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

10. Create a three dimensional array



In [12]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [13]:
x= np.arange(1,10)
print("Orignal Vector",x)

Orignal Vector [1 2 3 4 5 6 7 8 9]


In [14]:
print("Reverse Vector")
x = x[:-1]
print(x)

Reverse Vector
[1 2 3 4 5 6 7 8]


12. Create a null vector of size 10 but the fifth value which is 1 

In [15]:
x = np.zeros(10)
x
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [16]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [17]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
arr = arr.astype(float)
print(arr.dtype)

int32
float64


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [18]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
np.multiply(arr1,arr2)

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [19]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
np.in1d(arr1,arr2)

array([ True,  True, False,  True, False, False])

17. Extract all odd numbers from arr with values(0-9)

In [20]:
x = np.arange(0,10)
x
x = x[x%2==1]
x

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [21]:
x = np.arange(0,10)
x
x[x%2==1] = -1
x

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [22]:
arr = np.arange(10)
arr
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [23]:
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [27]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr2d[1,1]=12
print(arr2d[1,1])
print(arr2d)

12
[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [32]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [36]:
arr3d[0][:]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [41]:
arr2d = np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
arr2d[0]

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [45]:
arr2d[1]

array([5, 6, 7, 8, 9])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [48]:
arr2d = np.array([[0,1,2],[3,4,5],[6,7,8]])
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [50]:
arr2d[0:2,2]

array([2, 5])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [53]:
arr = np.random.randn(10)
arr

array([ 1.14084645, -0.7962092 , -2.02832878, -3.17320915, -0.28454845,
       -0.67417373,  0.52308164,  0.07034211,  0.17821445, -0.93071379])

In [56]:
print(np.max(arr))
print(np.min(arr))


1.1408464497848292
-3.173209149913183


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [57]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [60]:
np.intersect1d(a,b)

array([2, 4])

In [61]:
help(np.intersect1d)

Help on function intersect1d in module numpy:

intersect1d(ar1, ar2, assume_unique=False, return_indices=False)
    Find the intersection of two arrays.
    
    Return the sorted, unique values that are in both of the input arrays.
    
    Parameters
    ----------
    ar1, ar2 : array_like
        Input arrays. Will be flattened if not already 1D.
    assume_unique : bool
        If True, the input arrays are both assumed to be unique, which
        can speed up the calculation.  Default is False.
    return_indices : bool
        If True, the indices which correspond to the intersection of the two
        arrays are returned. The first instance of a value is used if there are
        multiple. Default is False.
    
        .. versionadded:: 1.15.0
    
    Returns
    -------
    intersect1d : ndarray
        Sorted 1D array of common and unique elements.
    comm1 : ndarray
        The indices of the first occurrences of the common values in `ar1`.
        Only provided if `retur

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [68]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b) #It will returns the positions where the elements of a & b match

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [69]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 1.15502405  0.36999776  0.25038477 -0.42328288]
 [-0.05020358  0.26271879  0.11185327 -1.34950552]
 [-0.98109193 -1.05757473  0.7548545  -1.29672973]
 [ 0.5835068  -0.76523832  0.15359137 -1.08428939]
 [ 0.45563073  0.04386623  0.47228672 -0.58770106]
 [ 0.8257295   0.62659358  0.26783699  2.00425519]
 [ 0.82080138  0.0492255   0.30772359  0.30989823]]


In [71]:
d=names[names != 'Will']
d

array(['Bob', 'Joe', 'Bob', 'Joe', 'Joe'], dtype='<U4')

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [86]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
d = names[(names != 'Bob') & (names != 'Will')]
d

array(['Joe', 'Joe', 'Joe'], dtype='<U4')

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [93]:
arr = np.arange(1,16).reshape(5,3)
print(arr)
print(arr.dtype)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
int32


In [94]:
arr.astype(float)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [96]:
rr = np.arange(1,17).reshape(2,2,4)
print(arr)
print(arr.dtype)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
int32


In [97]:
arr.astype(float)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

33. Swap axes of the array you created in Question 32

In [110]:
print(arr)
np.swapaxes(arr,0,1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


array([[ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14],
       [ 3,  6,  9, 12, 15]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [131]:
arr= np.random.rand(1,10)
arr

array([[0.4748122 , 0.24611586, 0.37037025, 0.8100717 , 0.8748677 ,
        0.38278214, 0.49153403, 0.47554808, 0.19932028, 0.2197476 ]])

In [132]:
sqrt = np.sqrt(arr)
sqrt[sqrt<0.5] = 0
sqrt

array([[0.68906618, 0.        , 0.60858052, 0.90003983, 0.93534362,
        0.6186939 , 0.70109488, 0.68959994, 0.        , 0.        ]])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [144]:
arr1 = np.random.rand(1,12)
arr2 = np.random.rand(1,12)
print("First Array\n",arr1)
print("Second Array\n",arr2)
print("\n")
max_arr = np.array(np.maximum(arr1,arr2))
print("The required Array is:\n",max_arr)

First Array
 [[0.40957295 0.83743943 0.64201268 0.74205844 0.67177331 0.68601473
  0.40955286 0.86232762 0.32101394 0.99767695 0.28526089 0.31800386]]
Second Array
 [[0.40921985 0.38034308 0.92352718 0.70288943 0.00746033 0.62928598
  0.53706431 0.53686534 0.67960873 0.01398518 0.96094232 0.35461336]]


The required Array is:
 [[0.40957295 0.83743943 0.92352718 0.74205844 0.67177331 0.68601473
  0.53706431 0.86232762 0.67960873 0.99767695 0.96094232 0.35461336]]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [146]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [151]:
arr_unique = np.unique(names)
print("The array with unique name is:\n",arr_unique)

print("\nThe sorted array is:\n",np.sort(arr_unique))

The array with unique name is:
 ['Bob' 'Joe' 'Will']

The sorted array is:
 ['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [159]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(a,"\n")
print(b,"\n")
result = np.setdiff1d(a, b)
print(result)

[1 2 3 4 5] 

[5 6 7 8 9] 

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [178]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print("Sample Array is:\n",sampleArray)
newColumn = np.array([[10,10,10]])
print("\nNew Column is:\n", newColumn)
sampleArray[:,1] = newColumn
print("\nRequired Array is:\n",sampleArray)


Sample Array is:
 [[34 43 73]
 [82 22 12]
 [53 94 66]]

New Column is:
 [[10 10 10]]

Required Array is:
 [[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [186]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print("x: \n",x)
print("y:\n",y)
dot_product = np.dot(x,y)
print("The result is: \n",dot_product)

x: 
 [[1. 2. 3.]
 [4. 5. 6.]]
y:
 [[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]
The result is: 
 [[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [201]:
matrix = np.random.randn(1,20)
print("Orignal Matrix is:\n",matrix)
cum_sum = np.cumsum(matrix)
print("Cumulative sum is:\n",cum_sum)

Orignal Matrix is:
 [[ 1.22198268  0.11902368 -0.35577128 -1.12100576 -0.47152136  0.74530022
  -0.37483811  0.51896761  1.28665726 -0.52080812 -0.21982915 -0.7747531
   0.2678658   2.51263093 -0.50922221 -1.09470628  1.49824932 -0.23367382
  -0.27940726 -0.58130479]]
Cumulative sum is:
 [ 1.22198268  1.34100636  0.98523509 -0.13577067 -0.60729202  0.1380082
 -0.23682992  0.28213769  1.56879495  1.04798683  0.82815768  0.05340458
  0.32127038  2.8339013   2.32467909  1.22997282  2.72822213  2.49454831
  2.21514105  1.63383626]
