# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
import numpy as np
arr1d = np.arange(10)
print(arr1d)
arr2d = np.reshape(arr1d,(2,-1))
arr2d

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [16]:
arr1 = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
arr2 = np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])
np.vstack((arr1,arr2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [25]:
a1 = np.array([0, 1, 2, 3, 4, 1, 1, 1, 1, 1])
a2 = np.array([5, 6, 7, 8, 9, 1, 1, 1, 1, 1])
print(a1)
print(a2)
np.stack((a1,a2))

[0 1 2 3 4 1 1 1 1 1]
[5 6 7 8 9 1 1 1 1 1]


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [41]:
nd = np.array([[0,1,2,3,4],[5,6,7,8,9]])
print("ND Array is:\n",nd)
print("\nThe desired array is:")
nd.flatten()

ND Array is:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

The desired array is:


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [56]:
nd = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])
#nd.reshape(-1)
#nd.ravel()
nd.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [69]:
nd = np.array([[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]])
print(nd)
nd.reshape(5,3)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [90]:
x= np.ones((5,5))
x+=np.arange(5)
print(x)
np.square(x)

[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]


array([[ 1.,  4.,  9., 16., 25.],
       [ 1.,  4.,  9., 16., 25.],
       [ 1.,  4.,  9., 16., 25.],
       [ 1.,  4.,  9., 16., 25.],
       [ 1.,  4.,  9., 16., 25.]])

## Question:8

### Create 5x6 an array and find the mean?

In [95]:
arr = np.ones((5,6))
arr+=np.arange(6)
print(arr)
np.mean(arr)

[[1. 2. 3. 4. 5. 6.]
 [1. 2. 3. 4. 5. 6.]
 [1. 2. 3. 4. 5. 6.]
 [1. 2. 3. 4. 5. 6.]
 [1. 2. 3. 4. 5. 6.]]


3.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [96]:
np.std(arr)

1.707825127659933

## Question:10

### Find the median of the previous array in Q8?

In [97]:
np.median(arr)

3.5

## Question:11

### Find the transpose of the previous array in Q8?

In [98]:
np.transpose(arr)

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6.]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [101]:
x= np.ones((4,4))
x+=np.arange(4)
print(x)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [103]:
d_sum = np.trace(x)
d_sum

10.0

## Question:13

### Find the determinant of the previous array in Q12?

In [109]:
help(np.linalg.det)

Help on function det in module numpy.linalg:

det(a)
    Compute the determinant of an array.
    
    Parameters
    ----------
    a : (..., M, M) array_like
        Input array to compute determinants for.
    
    Returns
    -------
    det : (...) array_like
        Determinant of `a`.
    
    See Also
    --------
    slogdet : Another way to represent the determinant, more suitable
      for large matrices where underflow/overflow may occur.
    scipy.linalg.det : Similar function in SciPy.
    
    Notes
    -----
    
    .. versionadded:: 1.8.0
    
    Broadcasting rules apply, see the `numpy.linalg` documentation for
    details.
    
    The determinant is computed via LU factorization using the LAPACK
    routine ``z/dgetrf``.
    
    Examples
    --------
    The determinant of a 2-D array [[a, b], [c, d]] is ad - bc:
    
    >>> a = np.array([[1, 2], [3, 4]])
    >>> np.linalg.det(a)
    -2.0 # may vary
    
    Computing determinants for a stack of matrices:
    
 

In [108]:
np.linalg.det(x)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [114]:
print("5ht Percentile is:  ",np.percentile(x,5))
print("\n95th Percentile is: ",np.percentile(x,95))

5ht Percentile is:   1.0

95th Percentile is:  4.0


## Question:15

### How to find if a given array has any null values?

In [115]:
np.isnan(x)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])